variables:
  STABLE_VERSION: "0.13"
  STABLE_IMAGE_NAME: "$CI_REGISTRY_IMAGE/stable:latest"
  BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/branches/$CI_COMMIT_REF_SLUG-$TERRAFORM_VERSION:$CI_COMMIT_SHA"
  RELEASE_IMAGE_NAME: "$CI_REGISTRY_IMAGE/releases/$TERRAFORM_VERSION"
  TF_ADDRESS: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/terraform/state/$CI_JOB_ID"

stages:
  - lint
  - build
  - test
  - prepare-release
  - release

.dind: &dind
  services:
    - docker:19.03.5-dind
  image: docker:19.03.5
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

.build: &build
  <<: *dind
  stage: build
  script:
    - docker image build --tag "$BUILD_IMAGE_NAME" --build-arg BASE=$TERRAFORM_BASE .
    - docker image push "$BUILD_IMAGE_NAME"

.test-unit: &test-unit
  stage: test
  image: "$BUILD_IMAGE_NAME"
  script:
    - terraform version
    - gitlab-terraform version
    - jq --version
    - cd tests
    - gitlab-terraform init
    - gitlab-terraform plan
    - if [[ ! -f "plan.cache" ]]; then echo "expected to find a plan.cache file"; exit 1; fi
    - gitlab-terraform plan-json
    - if [[ ! -f "plan.json" ]]; then echo "expected to find a plan.json file"; exit 1; fi
    - gitlab-terraform apply

.release: &release
  <<: *dind
  stage: release
  script:
    - docker image pull "$BUILD_IMAGE_NAME"
    - docker image tag "$BUILD_IMAGE_NAME" "$RELEASE_IMAGE_NAME:latest"
    - docker image tag "$BUILD_IMAGE_NAME" "$RELEASE_IMAGE_NAME:$CI_COMMIT_TAG"
    - docker image push "$RELEASE_IMAGE_NAME:latest"
    - docker image push "$RELEASE_IMAGE_NAME:$CI_COMMIT_TAG"
    - if [ "$TERRAFORM_VERSION" = "$STABLE_VERSION" ]; then docker image tag "$BUILD_IMAGE_NAME" "$STABLE_IMAGE_NAME"; fi
    - if [ "$TERRAFORM_VERSION" = "$STABLE_VERSION" ]; then docker image push "$STABLE_IMAGE_NAME"; fi

  only:
    - tags

.terraform-0.13: &terraform013
  variables:
    TERRAFORM_BASE: "hashicorp/terraform:0.13.2"
    TERRAFORM_VERSION: "0.13"

.terraform-0.12: &terraform012
  variables:
    TERRAFORM_BASE: "hashicorp/terraform:0.12.29"
    TERRAFORM_VERSION: "0.12"

shell check:
  stage: lint
  image: koalaman/shellcheck-alpine:stable
  before_script:
    - shellcheck --version
  script:
    - shellcheck src/**/*.sh

build 0.13:
  <<: *terraform013
  <<: *build

build 0.12:
  <<: *terraform012
  <<: *build

test-unit 0.13:
  <<: *terraform013
  <<: *test-unit

test-unit 0.12:
  <<: *terraform012
  <<: *test-unit

release 0.13:
  <<: *terraform013
  <<: *release

release 0.12:
  <<: *terraform012
  <<: *release

.semantic-release:
  image: node:12-buster-slim
  stage: prepare-release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab
  script:
    - semantic-release $DRY_RUN_OPT -b $CI_COMMIT_REF_NAME

tag_release-dryrun:
  extends: .semantic-release
  variables:
    DRY_RUN_OPT: "-d"
  only:
    refs:
      - branches@gitlab-org/terraform-images
  except:
    refs:
      - master

tag_release:
  extends: .semantic-release
  only:
    refs:
      - master@gitlab-org/terraform-images
